name: Deploy to Production

on:
  push:
    branches:
      - main
    # Optionally configure to run only for specific files. For example:
    # paths:
    # - "website/**"

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # Add any build steps here. For example:
        env:
          REACT_APP_API_KEY: ${{secrets.REACT_APP_API_KEY}}
          REACT_APP_AUTH_DOMAIN: ${{secrets.REACT_APP_AUTH_DOMAIN}}
          REACT_APP_PROJECT_ID: ${{secrets.REACT_APP_PROJECT_ID}}
          REACT_APP_STORAGE_BUCKET: ${{secrets.REACT_APP_STORAGE_BUCKET}}
          REACT_APP_MESSAGING_SENDER_ID: ${{secrets.REACT_APP_MESSAGING_SENDER_ID}}
          REACT_APP_APP_ID: ${{secrets.REACT_APP_APP_ID}}
          REACT_APP_MEASUREMENT_ID: ${{secrets.REACT_APP_MEASUREMENT_ID}}
          REACT_APP_SQUIRE_API_URL: ${{secrets.REACT_APP_SQUIRE_API_URL}}
      - run: |
          export REACT_APP_API_KEY= ${{secrets.REACT_APP_API_KEY}}
          export REACT_APP_AUTH_DOMAIN= ${{secrets.REACT_APP_AUTH_DOMAIN}}
          export REACT_APP_PROJECT_ID= ${{secrets.REACT_APP_PROJECT_ID}}
          export REACT_APP_STORAGE_BUCKET= ${{secrets.REACT_APP_STORAGE_BUCKET}}
          export REACT_APP_MESSAGING_SENDER_ID= ${{secrets.REACT_APP_MESSAGING_SENDER_ID}}
          export REACT_APP_APP_ID= ${{secrets.REACT_APP_APP_ID}}
          export REACT_APP_MEASUREMENT_ID= ${{secrets.REACT_APP_MEASUREMENT_ID}}
          export REACT_APP_SQUIRE_API_URL= ${{secrets.REACT_APP_SQUIRE_API_URL}}
          && cd squire-frontend && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: ./squire-frontend
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: squire-backend-5c68c
          channelId: live
